Vagrant::Config.run do |config|
  # Host config
  config.vm.define :host do |host_config|
      if ! ENV['GLANCEIMAGES']
        raise ArgumentError, "GLANCEIMAGES environment variable not defined."
      end
      if ! ENV['GLANCESRC']
        raise ArgumentError, "GLANCESRC environment variable not defined."
      end

      # Assign this VM to a host only network IP, allowing you to access it
      # via the IP. The IP for the volume vm is "33.33.33.10"
      host_config.vm.network "33.33.33.11"

      host_config.vm.box = "lucid_ext3_openvz"
      host_config.vm.box_url = "http://c629296.r96.cf2.rackcdn.com/#{config.vm.box}.box"

      host_config.vm.share_folder "glance", "/glance", ENV['GLANCESRC']
      host_config.vm.share_folder "glance_images", "/glance_images", ENV['GLANCEIMAGES']
      host_config.vm.share_folder "nova", "/src", "../../../"
      if ENV['RSDNS']
        rsdns_dir = ENV['RSDNS']
        if File.directory?(rsdns_dir)
            host_config.vm.share_folder "rsdns", "/rsdns", ENV['RSDNS']
        end
      end
      host_config.vm.share_folder "vagrant-common", "/vagrant-common", "./../common"
      host_config.vm.share_folder "tests", "/tests", "./../../"
  end

  # Volume Config
  config.vm.define :volume do |volume_config|
    volume_config.vm.box = "volumeserver"
    volume_config.vm.network "33.33.33.10"
  end
end
